# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-10-26 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_designer', '0003_mail_cover_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdefinitionfield',
            name='help_text',
            field=models.TextField(blank=True, null=True, verbose_name='help text'),
        ),
    ]
